version: '3.9'

services:
  web:
    container_name: xo-game-web
    build: .
    command: sh -c "flask db upgrade && flask run -h 0.0.0.0" #python manage.py
    volumes:
      - .:/code/
    ports:
      - "5000:5000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: xo-game-pg
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env.dev

volumes:
  postgres_data: