"""empty message

Revision ID: 618a9a523349
Revises: bf9826a6e2e8
Create Date: 2021-05-24 23:16:24.120655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618a9a523349'
down_revision = 'bf9826a6e2e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('total_turns', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'total_turns')
    # ### end Alembic commands ###
