"""Initial migration

Revision ID: bf9826a6e2e8
Revises: 
Create Date: 2021-05-23 21:07:36.764185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf9826a6e2e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_mark', sa.Enum('X', 'O', name='marktype'), nullable=False),
    sa.Column('result', sa.Enum('WIN', 'LOSE', 'DRAW', name='gameresulttype'), nullable=True),
    sa.Column('overview', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('started_dttm', sa.DateTime(), nullable=False),
    sa.Column('finished_dttm', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('users')
    # ### end Alembic commands ###
