"""Change mark type

Revision ID: 2df79084a008
Revises: 3ddcad880b56
Create Date: 2023-11-27 16:56:31.552608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df79084a008'
down_revision = '3ddcad880b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_x_game', 'mark')
    op.add_column('user_x_game', sa.Column('mark', sa.String(1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_x_game', 'mark')
    # ### end Alembic commands ###
