"""Change nullable property for game_result field

Revision ID: 543be485b2b9
Revises: 80fb0e83358b
Create Date: 2023-11-27 20:59:24.874675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543be485b2b9'
down_revision = '80fb0e83358b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_x_game', 'game_result',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_x_game', 'game_result',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
