"""Add league table

Revision ID: 55566183e8d0
Revises: 543be485b2b9
Create Date: 2023-11-30 22:10:32.958347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55566183e8d0'
down_revision = '543be485b2b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('game', sa.Column('league_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game', 'league', ['league_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'league_id')
    op.drop_table('league')
    # ### end Alembic commands ###
