"""Update options field

Revision ID: 6ca49c4786a2
Revises: 57b1052584ec
Create Date: 2023-12-05 22:25:21.490282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ca49c4786a2'
down_revision = '57b1052584ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('user', 'options')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('user', 'profile_options')
    # ### end Alembic commands ###
