"""Rename overview field

Revision ID: 80fb0e83358b
Revises: 2df79084a008
Create Date: 2023-11-27 17:15:19.705814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80fb0e83358b'
down_revision = '2df79084a008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('turns_overview', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('game', 'overview')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('overview', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('game', 'turns_overview')
    # ### end Alembic commands ###
